name: thesis-pipeline
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - scipy
  - matplotlib
  - rasterio=1.3.6
  - gdal=3.6.2
  - sqlite
  - open3d=0.19.0
  - pdal=2.8.4
  - python-pdal=3.4.5
  - pip
  - pip:
      - torch==2.0.1
      - torchvision==0.15.2
      - json5
      - opencv-python  
