name: thesis-pipeline
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _x86_64-microarch-level=3
  - affine=2.4.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.12.0
  - aiosignal=1.3.2
  - alsa-lib=1.2.14
  - aom=3.9.1
  - assimp=5.4.3
  - async-timeout=5.0.1
  - attr=2.5.1
  - attrs=25.3.0
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.0
  - aws-c-common=0.12.3
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.4
  - aws-c-http=0.10.1
  - aws-c-io=0.19.0
  - aws-c-mqtt=0.13.0
  - aws-c-s3=0.7.17
  - aws-c-sdkutils=0.2.3
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.32.5
  - aws-sdk-cpp=1.11.510
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - blinker=1.9.0
  - blosc=1.21.6
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.4.26
  - cairo=1.18.4
  - capnproto=1.0.2
  - ceres-solver=2.2.0
  - certifi=2025.4.26
  - cffi=1.17.1
  - charset-normalizer=3.4.2
  - click=8.2.1
  - click-plugins=1.1.1
  - cligj=0.7.2
  - contourpy=1.3.2
  - cpd=0.5.5
  - cpp-expected=1.1.0
  - cycler=0.12.1
  - cyrus-sasl=2.1.27
  - dash=3.0.4
  - dav1d=1.2.1
  - dbus=1.13.6
  - double-conversion=3.3.1
  - draco=1.5.7
  - eigen=3.4.0
  - embree=4.3.3
  - expat=2.7.0
  - fgt=0.4.11
  - flask=3.1.1
  - fmt=11.1.4
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.58.0
  - freetype=2.13.3
  - freexl=2.0.0
  - frozenlist=1.6.0
  - gdal=3.10.2
  - geos=3.13.1
  - geotiff=1.7.4
  - gflags=2.2.2
  - giflib=5.2.2
  - gl2ps=1.4.2
  - glew=2.1.0
  - glfw=3.4
  - glog=0.7.1
  - gmp=6.3.0
  - graphite2=1.3.13
  - h2=4.2.0
  - harfbuzz=11.0.0
  - hdf4=4.2.15
  - hdf5=1.14.3
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.7.0
  - itsdangerous=2.2.0
  - jinja2=3.1.6
  - json-c=0.18
  - jsoncpp=1.9.6
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20250127.1
  - libaec=1.1.3
  - libamd=3.3.3
  - libarchive=3.7.7
  - libarrow=18.1.0
  - libarrow-acero=18.1.0
  - libarrow-dataset=18.1.0
  - libavif16=1.3.0
  - libblas=3.9.0
  - libboost=1.86.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libbtf=2.3.2
  - libcamd=3.3.3
  - libcap=2.75
  - libcblas=3.9.0
  - libccolamd=3.3.4
  - libcholmod=5.3.1
  - libclang-cpp20.1=20.1.5
  - libclang13=20.1.5
  - libcolamd=3.3.4
  - libcrc32c=1.1.2
  - libcups=2.3.3
  - libcurl=8.13.0
  - libcxsparse=4.4.1
  - libde265=1.0.15
  - libdeflate=1.23
  - libdrm=2.4.124
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.0
  - libfabric=2.1.0
  - libfabric1=2.1.0
  - libffi=3.4.4
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgcrypt-lib=1.11.1
  - libgdal-arrow-parquet=3.10.2
  - libgdal-core=3.10.2
  - libgdal-hdf5=3.10.2
  - libgdal-pg=3.10.2
  - libgdal-postgisraster=3.10.2
  - libgdal-tiledb=3.10.2
  - libgfortran=15.1.0
  - libgfortran-ng=15.1.0
  - libgfortran5=15.1.0
  - libgl=1.7.0
  - libglib=2.84.0
  - libglu=9.0.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.1.0
  - libgoogle-cloud=2.36.0
  - libgoogle-cloud-storage=2.36.0
  - libgpg-error=1.55
  - libgrpc=1.71.0
  - libheif=1.19.7
  - libhwloc=2.11.2
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - libklu=2.3.5
  - libkml=1.3.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libldl=3.3.2
  - libllvm20=20.1.5
  - liblzf=3.6
  - liblzma=5.8.1
  - libmamba=2.1.1
  - libnetcdf=4.9.2
  - libnghttp2=1.64.0
  - libnl=3.11.0
  - libnsl=2.0.1
  - libntlm=1.8
  - libogg=1.3.5
  - libopenblas=0.3.29
  - libopengl=1.7.0
  - libparquet=18.1.0
  - libparu=1.0.0
  - libpciaccess=0.18
  - libpdal=2.8.4
  - libpdal-arrow=2.8.4
  - libpdal-core=2.8.4
  - libpdal-cpd=2.8.4
  - libpdal-draco=2.8.4
  - libpdal-e57=2.8.4
  - libpdal-hdf=2.8.4
  - libpdal-icebridge=2.8.4
  - libpdal-nitf=2.8.4
  - libpdal-pgpointcloud=2.8.4
  - libpdal-tiledb=2.8.4
  - libpdal-trajectory=2.8.4
  - libpmix=5.0.8
  - libpng=1.6.47
  - libpq=17.5
  - libprotobuf=5.29.3
  - librbio=4.3.4
  - libre2-11=2024.07.02
  - librttopo=1.1.0
  - libsodium=1.0.20
  - libsolv=0.7.32
  - libspatialite=5.1.0
  - libspex=3.2.3
  - libspqr=4.3.4
  - libsqlite=3.49.2
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libsuitesparseconfig=7.10.1
  - libsystemd0=257.4
  - libtheora=1.1.1
  - libthrift=0.21.0
  - libtiff=4.7.0
  - libudev1=257.4
  - libumfpack=6.3.5
  - libutf8proc=2.10.0
  - libuuid=2.38.1
  - libvorbis=1.3.7
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.10.0
  - libxml2=2.13.8
  - libxslt=1.1.39
  - libzip=1.11.2
  - libzlib=1.3.1
  - loguru=0.7.3
  - lz4-c=1.10.0
  - lzo=2.10
  - mamba=2.1.1
  - markupsafe=3.0.2
  - matplotlib=3.10.3
  - matplotlib-base=3.10.3
  - metis=5.1.0
  - minizip=4.0.10
  - mpfr=4.2.1
  - mpi=1.0
  - msgpack-python=1.1.0
  - multidict=6.4.4
  - munkres=1.1.4
  - mysql-common=9.0.1
  - mysql-libs=9.0.1
  - narwhals=1.40.0
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nitro=2.7.dev8
  - nlohmann_json=3.11.3
  - numpy=1.26.4
  - openjpeg=2.5.3
  - openldap=2.6.10
  - openmpi=5.0.7
  - openssl=3.5.0
  - orc=2.1.2
  - packaging=25.0
  - pcre2=10.44
  - pdal=2.8.4
  - pillow=11.2.1
  - pip=25.1
  - pixman=0.46.0
  - plotly=6.1.1
  - postgresql=17.5
  - proj=9.5.1
  - propcache=0.3.1
  - pthread-stubs=0.4
  - pugixml=1.15
  - pycparser=2.22
  - pyparsing=3.2.3
  - pyside6=6.8.3
  - pysocks=1.7.1
  - python=3.10.17
  - python-dateutil=2.9.0.post0
  - python-pdal=3.4.5
  - python_abi=3.10
  - qhull=2020.2
  - qt6-main=6.8.3
  - rasterio=1.4.3
  - rav1e=0.7.1
  - rdma-core=57.0
  - re2=2024.07.02
  - readline=8.2
  - reproc=14.2.5.post0
  - reproc-cpp=14.2.5.post0
  - requests=2.32.3
  - retrying=1.3.4
  - s2n=1.5.18
  - scipy=1.15.2
  - setuptools=78.1.1
  - simdjson=3.12.3
  - six=1.17.0
  - snappy=1.2.1
  - snuggs=1.4.7
  - spdlog=1.15.3
  - sqlite=3.49.2
  - suitesparse=7.10.1
  - svt-av1=3.0.2
  - tbb=2022.1.0
  - tiledb=2.27.2
  - tinyobjloader=1.0.7
  - tk=8.6.13
  - tornado=6.5.1
  - typing-extensions=4.13.2
  - typing_extensions=4.13.2
  - tzcode=2025b
  - ucc=1.4.4
  - ucx=1.18.1
  - unicodedata2=16.0.0
  - uriparser=0.9.8
  - urllib3=2.4.0
  - utfcpp=4.0.6
  - vtk-base=9.3.1
  - wayland=1.23.1
  - werkzeug=3.1.3
  - wheel=0.45.1
  - wslink=2.3.4
  - x265=3.5
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xerces-c=3.2.5
  - xkeyboard-config=2.44
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxinerama=1.1.5
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxt=1.3.1
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - yaml-cpp=0.8.0
  - yarl=1.20.0
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - addict==2.4.0
      - asttokens==3.0.0
      - comm==0.2.2
      - configargparse==1.7.1
      - decorator==5.2.1
      - exceptiongroup==1.3.0
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - filelock==3.13.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - ipython==8.36.0
      - ipywidgets==8.1.7
      - jedi==0.19.2
      - joblib==1.5.1
      - jsonschema==4.23.0
      - jsonschema-specifications==2025.4.1
      - jupyter-core==5.8.0
      - jupyterlab-widgets==3.0.15
      - laspy==2.5.4
      - matplotlib-inline==0.1.7
      - mpmath==1.3.0
      - nbformat==5.10.4
      - networkx==3.3
      - open3d==0.19.0
      - opencv-python==4.11.0.86
      - pandas==2.2.3
      - parso==0.8.4
      - pdal-plugins==1.6.2
      - pexpect==4.9.0
      - platformdirs==4.3.8
      - prompt-toolkit==3.0.51
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pygments==2.19.1
      - pyquaternion==0.9.9
      - pytz==2025.2
      - pyyaml==6.0.2
      - referencing==0.36.2
      - rpds-py==0.25.1
      - scikit-learn==1.6.1
      - seaborn==0.13.2
      - smmap==5.0.2
      - stack-data==0.6.3
      - sympy==1.13.3
      - thop==0.1.1-2209072238
      - threadpoolctl==3.6.0
      - torch==2.0.1+cpu
      - torchvision==0.15.2+cpu
      - tqdm==4.67.1
      - traitlets==5.14.3
      - tzdata==2025.2
      - ultralytics==8.3.145
      - ultralytics-thop==2.0.14
      - wcwidth==0.2.13
      - widgetsnbextension==4.0.14
prefix: /home/aron/anaconda3/envs/thesis-pipeline
